openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
  description: APIs for user management and script emotion analysis
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: Authentication
    description: APIs for user login and registration
  - name: ScriptAI
    description: APIs for script emotion analysis and management
paths:
  /auth/login:
    $ref: "./openapi/auth/login.yaml#/paths/~1auth~1login"
  /auth/register:
    $ref: "./openapi/auth/register.yaml#/paths/~1auth~1register"
  /auth/getToken:
    $ref: "./openapi/auth/get-token.yaml#/paths/~1auth~1getToken"
  /auth/refreshToken:
    $ref: "./openapi/auth/refresh-token.yaml#/paths/~1auth~1refreshToken"
  /scripts/presampling:
    $ref: "./openapi/scripts/presampling.yaml#/paths/~1scripts~1presampling"
  /scripts/info:
    $ref: "./openapi/scripts/info.yaml#/paths/~1scripts~1info"
  /scripts/emotion-analysis:
    $ref: "./openapi/scripts/emotion-analysis.yaml#/paths/~1scripts~1emotion-analysis"
  /scripts/get-emotion-analysis:
    $ref: "./openapi/scripts/get-emotion-analysis.yaml#/paths/~1scripts~1emotion-analysis"
  /user/profileUpdate:
    $ref: "./openapi/user/profileUpdate.yaml#/paths/~1user~1profileUpdate"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
