openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
  description: APIs for user management and script emotion analysis
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: Authentication
    description: APIs for user login and registration
  - name: ScriptAI
    description: APIs for script emotion analysis and management
paths:
  /auth/login:
    $ref: "./openapi/auth/login.yaml#/paths/~1auth~1login"
  /auth/register:
    $ref: "./openapi/auth/register.yaml#/paths/~1auth~1register"
  /auth/getToken:
    $ref: "./openapi/auth/get-token.yaml#/paths/~1auth~1getToken"
  /auth/refreshToken:
    $ref: "./openapi/auth/refresh-token.yaml#/paths/~1auth~1refreshToken"
  /scripts/presampling:
    $ref: "./openapi/scripts/presampling.yaml#/paths/~1scripts~1presampling"
  /scripts/add-version:
    $ref: "./openapi/scripts/add-version.yaml#/paths/~1scripts~1add-version"
  /scripts/info:
    $ref: "./openapi/scripts/info.yaml#/paths/~1scripts~1info"
  /scripts/brand-analysis:
    $ref: "./openapi/scripts/brand-analysis.yaml#/paths/~1scripts~1brand-analysis"
  /scripts/script-summary:
    $ref: "./openapi/scripts/script-summary.yaml#/paths/~1scripts~1script-summary"
  /scripts/rating:
    $ref: "./openapi/scripts/rating.yaml#/paths/~1scripts~1rating"
  /scripts/emotion-analysis:
    $ref: "./openapi/scripts/emotion-analysis.yaml#/paths/~1scripts~1emotion-analysis"
  /scripts/scene-analysis:
    $ref: "./openapi/scripts/sceneAnalysis.yaml#/paths/~1scripts~1scene-analysis"
  /scripts/shot-list:
    $ref: "./openapi/scripts/shotList.yaml#/paths/~1scripts~1shot-list"
  /scripts/prompt-generator:
    $ref: "./openapi/scripts/promptGenerator.yaml#/paths/~1scripts~1prompt-generator"
  /scripts/story-plot:
    $ref: "./openapi/scripts/story-plot.yaml#/paths/~1scripts~1story-plot"
  /scripts/get-script:
    $ref: "./openapi/scripts/get-script.yaml#/paths/~1scripts~1get-script"
  /scripts/get-analysis:
    $ref: "./openapi/scripts/get-analysis.yaml#/paths/~1scripts~1get-analysis"
  /scripts/stream-audio:
    $ref: "./openapi/scripts/stream-audio.yaml#/paths/~1scripts~1stream-audio"
  /scripts/synthesize-audio:
    $ref: "./openapi/scripts/synthesize-audio.yaml#/paths/~1scripts~1synthesize-audio"
  /scripts/fram3AIImage:
    $ref: "./openapi/scripts/fram3AIImage.yaml#/paths/~1scripts~1fram3AIImage"
  /user/profileUpdate:
    $ref: "./openapi/user/profileUpdate.yaml#/paths/~1user~1profileUpdate"
  /user/profile:
    $ref: "./openapi/user/getProfile.yaml#/paths/~1user~1profile"
  /user/extendedInfo:
    $ref: "./openapi/user/extendedInfo.yaml#/paths/~1user~1extendedInfo"
  /artifacts/upload:
    $ref: "./openapi/artifacts/upload.yaml#/paths/~1artifacts~1upload"
  /artifacts/retrieve:
    $ref: "./openapi/artifacts/retrieve.yaml#/paths/~1artifacts~1retrieve"
  /artifacts/delete:
    $ref: "./openapi/artifacts/delete.yaml#/paths/~1artifacts~1delete"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
